<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    
    <!-- All dimensions multiplied by a factor of 10 for simulation -->
    <!-- <box size="0.067 0.143 0.0425"/>    -->
    <xacro:property name="bp_length" value="0.67" />
    <xacro:property name="bp_width" value="1.43" />
    <xacro:property name="bp_height" value="0.425" />

    <!-- Link 1 -->
    <xacro:property name="l1_radius" value="0.35" />
    <xacro:property name="l1_height" value="0.04" />
    
    <!-- Link 1 and 2 offset -->
    <xacro:property name="l12_offset" value="0.3925" />
    
    <!-- Link 2 and 3 offset -->
    <xacro:property name="l23_offset" value="0.674" />

    <!-- Link 2 -->
    <xacro:property name="l2_length" value="0.452" />
    <xacro:property name="l2_width" value="0.243" />
    <xacro:property name="l2_height" value="1.115" />

    <!-- Link 3 -->
    <xacro:property name="l3_length" value="0.48" />
    <xacro:property name="l3_width" value="0.20" />
    <xacro:property name="l3_height" value="0.404" />

    <!-- Link 4 -->
    <xacro:property name="l4_length" value="0.56" />
    <xacro:property name="l4_width" value="0.20" />
    <xacro:property name="l4_height" value="0.20" />

    <xacro:property name="effort" value="30"/>
    <xacro:property name="velocity" value="10"/>

    

    <link name="base_footprint_v1" />

    <link name="base_parrot">
        <visual>
            <geometry>
                <!-- Original Dimensions -->
                <box size="${bp_length} ${bp_width} ${bp_height}"/>   
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <!-- Original Dimensions -->
                <box size="${bp_length} ${bp_width} ${bp_height}"/>   
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:box_inertia m="1.0" 
                           l="${bp_length}" w="${bp_width}" h="${bp_height}" 
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="link_1">
        <visual>
            <geometry>
                <cylinder radius="${l1_radius}" length="${l1_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>    
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${l1_radius}" length="${l1_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${l1_radius}  " h="${l1_height}" 
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="link_2">
        <visual>
            <geometry>
                <box size="${l2_length} ${l2_width} ${l2_height}"/>  
            </geometry>
            <origin xyz="0 0 ${l2_height/2 - 0.2205}" rpy="0 0 0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${l2_length} ${l2_width} ${l2_height}"/>  
            </geometry>
            <origin xyz="0 0 ${l2_height/2 - 0.2205}" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="1.0" 
                           l="${l2_length}" w="${l2_width}" h="${l2_height}" 
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="link_3">
        <visual>
            <geometry>
                <box size="${l3_length} ${l3_width} ${l3_height}"/>
            </geometry>
            <origin xyz="0 0 0.674" rpy="0 0 0"/>
            <material name="red"/>
        </visual>
        <collision>
            <geometry>
                <box size="${l3_length} ${l3_width} ${l3_height}"/>
            </geometry>
            <origin xyz="0 0 0.674" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="1.0" 
                           l="${l3_length}" w="${l3_width}" h="${l3_height}" 
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="link_4">
        <visual>
            <geometry>
                <box size="${l4_length} ${l4_width} ${l4_height}"/>
            </geometry>
            <origin xyz="0 0 0.5603" rpy="0 0 0"/>
            <material name="green"/>
        </visual>
        <collision>
            <geometry>
                <box size="${l4_length} ${l4_width} ${l4_height}"/>
            </geometry>
            <origin xyz="0 0 0.5603" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="1.0" 
                           l="${l4_length}" w="${l4_width}" h="${l4_height}" 
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_footprint_link_joint" type="fixed">
        <parent link="base_footprint_v1"/>
        <child link="base_parrot"/>
        <origin xyz="0 0 ${bp_height /2}" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="base_j1_joint" type="revolute">
        <parent link="base_parrot"/>
        <child link="link_1"/>
        <origin xyz="0 0 ${bp_height/2 + l1_height/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${pi /2}" upper="${-pi /2}" effort="${effort}" velocity="${velocity}"/>
    </joint>

    <joint name="link_1_2_joint" type="revolute">
        <parent link="link_1"/>
        <child link="link_2"/>
        <origin xyz="0 0 0${l1_height/2 + l12_offset}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="${pi /2}" upper="${-pi /2}" effort="${effort}" velocity="${velocity}"/>
    </joint>
    
    <joint name="link_2_3_joint" type="revolute">
        <parent link="link_2"/>
        <child link="link_3"/>
        <origin xyz="0 0 0.674" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="${pi /2}" upper="${-pi /2}" effort="${effort}" velocity="${velocity}"/>
    </joint>

    <joint name="link_3_4_joint" type="revolute">
        <parent link="link_3"/>
        <child link="link_4"/>
        <origin xyz="0 0 0.674" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="${pi /2}" upper="${-pi /2}" effort="${effort}" velocity="${velocity}"/>
    </joint>

</robot>