#Request
# 3 Euler Angles to be converted to Quaternion
float64 roll
float64 pitch
float64 yaw
---
# Response
# 4 Elements of quaternion that are the result of the conversion
float64 x
float64 y
float64 z
float64 w