# Request
# 4 elements of quaternion that are to be converted
float64 x
float64 y
float64 z
float64 w
---
# Response
# 3 euler angles that are the result of the conversion
float64 roll
float64 pitch
float64 yaw