arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  # The below command only specifies the position of the gripper
  # As it is incapable of determining the orientation due to its limited DOF
  position_only_ik: True